Add osx launch script

diff --git a/bin/texvide b/bin/texvide
--- a/bin/texvide
+++ b/bin/texvide
@@ -1,13 +1,23 @@
 #!/bin/bash
 
-OS_TYPE=$(uname)
+HOST_OS=$(uname)
 
-if [[ "$OS_TYPE" == "Linux" ]]; then
+cleanup() {
+    if [ ! -z "$XPRA_PID" ]; then
+        kill -9 $XPRA_PID 2>/dev/null
+    fi
+}
+
+# Set up trap for cleanup
+trap cleanup EXIT
+
+if [[ "$HOST_OS" == "Linux" ]]; then
     xhost +local:docker >> /dev/null
 
     docker run \
-        --env="HOST_OS=Linux" \
-        --env="DISPLAY" \
+        --hostname TexVIDE \
+        --env="HOST_OS=${HOST_OS}" \
+        --env="DISPLAY=${DISPLAY}" \
         --volume="${HOME}:/home" \
         --volume="$(dirname "$0")/../config/:/root/.config" \
         --volume="/tmp/.X11-unix:/tmp/.X11-unix" \
@@ -15,19 +25,19 @@ if [[ "$OS_TYPE" == "Linux" ]]; then
         --volume="/run/user/1000/at-spi/bus_0:/run/user/1000/at-spi/bus_0:rw" \
         --rm \
         -it texvide
-
-elif [[ "$OS_TYPE" == "Darwin" ]]; then
-    # xhost + 127.0.0.1 >> /dev/null
+elif [[ "$HOST_OS" == "Darwin" ]]; then
+    "$(dirname "$0")/../venv/bin/python3" "$(dirname "$0")/../launch_xpra.py" > /dev/null 2>&1 &
+    XPRA_PID=$!
 
     docker run \
-        --env="HOST_OS=Darwin" \
+        --hostname TexVIDE \
+        --env="HOST_OS=${HOST_OS}" \
         --env="DISPLAY=:80" \
         --volume="${HOME}:/home" \
         --volume="$(dirname "$0")/../config/:/root/.config" \
         -p 8080:8080 \
         --rm \
         -it texvide
-
 else
-    echo "Unsupported OS: ${OS_TYPE}"
+    echo "Unsupported OS: ${HOST_OS}"
 fi
