Ensure linux support has not been broken

diff --git a/bin/texvide b/bin/texvide
--- a/bin/texvide
+++ b/bin/texvide
@@ -1,4 +1,12 @@
 #!/bin/bash
 
-source "$(dirname "$0")/venv/bin/activate"
-python3 "$(dirname "$0")/texvide.py"
+set -e
+
+# Check if Docker image "texvide" exists
+if ! docker image inspect texvide >/dev/null 2>&1; then
+    echo "Docker image 'texvide' not found. Please build the image and run this script again."
+    exit 1
+fi
+
+
+"$(dirname "$0")/../venv/bin/python3" "$(dirname "$0")/texvide.py"
